Repository celo-org/optics-monorepo, pull requests merged in 2021-05, with the labels that each got.

#355 update README.md
  README.md
Labels: chore

#334 test: GovernanceRouter upgrade and setUpdater calls
  solidity/optics-core/contracts/governance/GovernanceMessage.sol
  solidity/optics-core/contracts/test/TestGovernanceRouter.sol
  solidity/optics-core/contracts/test/TestRecipient.sol
  solidity/optics-core/lib/index.js
  solidity/optics-core/lib/utils.js
  solidity/optics-core/test/cross-chain/GovernanceRouter.test.js
  solidity/optics-core/test/cross-chain/SimpleMessage.test.js
  solidity/optics-core/test/cross-chain/crossChainTestUtils.js
  solidity/optics-core/test/cross-chain/deployCrossChainTest.js
Labels: solidity/js ♦️, testing

#362 fix: handles undefined GITHUB_TOKEN
  .github/workflows/mergify.yml
Labels: bug, repo-setup
